# Generated by Django 2.2 on 2021-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_auto_20210910_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_desc',
            field=models.CharField(default='None', max_length=300),
            preserve_default=False,
        ),
    ]
